In [5]:
import pandas as pd

In [6]:
archivo = (r"C:\Users\Usuario\Desktop\escritorio\DA-DS\datasets\Mobiles_Dataset_2025.csv")

In [7]:
df = pd.read_csv(archivo, encoding="ISO-8859-1")

In [8]:
print(df.head())

  Company Name            Model Name Mobile Weight  RAM Front Camera  \
0        Apple       iPhone 16 128GB          174g  6GB         12MP
1        Apple       iPhone 16 256GB          174g  6GB         12MP
2        Apple       iPhone 16 512GB          174g  6GB         12MP
3        Apple  iPhone 16 Plus 128GB          203g  6GB         12MP
4        Apple  iPhone 16 Plus 256GB          203g  6GB         12MP

  Back Camera   Processor Battery Capacity Screen Size  \
0        48MP  A17 Bionic         3,600mAh  6.1 inches
1        48MP  A17 Bionic         3,600mAh  6.1 inches
2        48MP  A17 Bionic         3,600mAh  6.1 inches
3        48MP  A17 Bionic         4,200mAh  6.7 inches
4        48MP  A17 Bionic         4,200mAh  6.7 inches

  Launched Price (Pakistan) Launched Price (India) Launched Price (China)  \
0               PKR 224,999             INR 79,999              CNY 5,799
1               PKR 234,999             INR 84,999              CNY 6,099
2               PKR 244,999             INR 89,999              CNY 6,499
3               PKR 249,999             INR 89,999              CNY 6,199
4               PKR 259,999             INR 94,999              CNY 6,499

  Launched Price (USA) Launched Price (Dubai)  Launched Year
0              USD 799              AED 2,799           2024
1              USD 849              AED 2,999           2024
2              USD 899              AED 3,199           2024
3              USD 899              AED 3,199           2024
4              USD 949              AED 3,399           2024

In [9]:
print(df.shape[0])

930

In [10]:
df = df.dropna()

In [11]:
#comprobando existencia de datos nulos
print(df.isnull().sum())

Company Name                 0
Model Name                   0
Mobile Weight                0
RAM                          0
Front Camera                 0
Back Camera                  0
Processor                    0
Battery Capacity             0
Screen Size                  0
Launched Price (Pakistan)    0
Launched Price (India)       0
Launched Price (China)       0
Launched Price (USA)         0
Launched Price (Dubai)       0
Launched Year                0
dtype: int64

In [12]:
print(df.dtypes)

Company Name                 object
Model Name                   object
Mobile Weight                object
RAM                          object
Front Camera                 object
Back Camera                  object
Processor                    object
Battery Capacity             object
Screen Size                  object
Launched Price (Pakistan)    object
Launched Price (India)       object
Launched Price (China)       object
Launched Price (USA)         object
Launched Price (Dubai)       object
Launched Year                 int64
dtype: object

In [13]:
df = df.rename(columns={"Company Name":"Compañia", "Model Name": "Modelo", "Mobile Weight":"Peso",
"Front Camera": "camara frontal",                 
"Back Camera": "camara trasera",               
"Processor": "procesador",                  
"Battery Capacity": "bateria",            
"Screen Size": "tamaño pantalla",                 
"Launched Price (Pakistan)": "precio lanzamiento (Pakistan)",   
"Launched Price (India)": "precio lanzamiento (India)",       
"Launched Price (China)": "precio lanzamiento (China)",            
"Launched Price (USA)": "precio lanzamiento (USA)",        
"Launched Price (Dubai)": "precio lanzamiento (Dubai)",       
"Launched Year": "año de lanzamiento" 
                        })

In [14]:
df = df.drop_duplicates()

In [15]:
print(df.shape[0])

915

In [16]:
df.dtypes

Compañia                         object
Modelo                           object
Peso                             object
RAM                              object
camara frontal                   object
camara trasera                   object
procesador                       object
bateria                          object
tamaño pantalla                  object
precio lanzamiento (Pakistan)    object
precio lanzamiento (India)       object
precio lanzamiento (China)       object
precio lanzamiento (USA)         object
precio lanzamiento (Dubai)       object
año de lanzamiento                int64
dtype: object

In [17]:
print(df.head())

  Compañia                Modelo  Peso  RAM camara frontal camara trasera  \
0    Apple       iPhone 16 128GB  174g  6GB           12MP           48MP
1    Apple       iPhone 16 256GB  174g  6GB           12MP           48MP
2    Apple       iPhone 16 512GB  174g  6GB           12MP           48MP
3    Apple  iPhone 16 Plus 128GB  203g  6GB           12MP           48MP
4    Apple  iPhone 16 Plus 256GB  203g  6GB           12MP           48MP

   procesador   bateria tamaño pantalla precio lanzamiento (Pakistan)  \
0  A17 Bionic  3,600mAh      6.1 inches                   PKR 224,999
1  A17 Bionic  3,600mAh      6.1 inches                   PKR 234,999
2  A17 Bionic  3,600mAh      6.1 inches                   PKR 244,999
3  A17 Bionic  4,200mAh      6.7 inches                   PKR 249,999
4  A17 Bionic  4,200mAh      6.7 inches                   PKR 259,999

  precio lanzamiento (India) precio lanzamiento (China)  \
0                 INR 79,999                  CNY 5,799
1                 INR 84,999                  CNY 6,099
2                 INR 89,999                  CNY 6,499
3                 INR 89,999                  CNY 6,199
4                 INR 94,999                  CNY 6,499

  precio lanzamiento (USA) precio lanzamiento (Dubai)  año de lanzamiento
0                  USD 799                  AED 2,799                2024
1                  USD 849                  AED 2,999                2024
2                  USD 899                  AED 3,199                2024
3                  USD 899                  AED 3,199                2024
4                  USD 949                  AED 3,399                2024

In [18]:
df.to_excel(r"C:\Users\Usuario\Desktop\escritorio\DA-DS\datasets\mobiles_limpio.xlsx", index=False)  # O usamos .to_csv y .csv si queremos tal formato

In [19]:
exchange_rates = {
    'PKR': 0.0036,  # 1 PKR = 0.0036 USD
    'INR': 0.012,   # 1 INR = 0.012 USD
    'CNY': 0.14,    # 1 CNY = 0.14 USD
    'USD': 1.0,     # 1 USD = 1 USD
    'AED': 0.27     # 1 AED = 0.27 USD
}

# Columnas que procesar
columns_to_change = ['precio lanzamiento (Pakistan)', 'precio lanzamiento (India)',
                     'precio lanzamiento (China)', 'precio lanzamiento (USA)', 
                     'precio lanzamiento (Dubai)']

# convertir a USD
for col in columns_to_change:
    df[col] = df[col].astype(str)  # asegurar el tipo como string
    df[col + ' (USD)'] = df[col].apply(
        lambda x: exchange_rates.get(x.split()[0], None) * float(x.split()[1].replace(',', '')) 
        if isinstance(x, str) and len(x.split()) == 2 and x.split()[0] in exchange_rates else None
    )
df = df.drop(columns=columns_to_change)

In [20]:
df.head()

,Compañia,Modelo,Peso,RAM,camara frontal,camara trasera,procesador,bateria,tamaño pantalla,año de lanzamiento,precio lanzamiento (Pakistan) (USD),precio lanzamiento (India) (USD),precio lanzamiento (China) (USD),precio lanzamiento (USA) (USD),precio lanzamiento (Dubai) (USD)
0,Apple,iPhone 16 128GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,2024,809.9964,959.988,811.86,799.0,755.73
1,Apple,iPhone 16 256GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,2024,845.9964,1019.988,853.86,849.0,809.73
2,Apple,iPhone 16 512GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,2024,881.9964,1079.988,909.86,899.0,863.73
3,Apple,iPhone 16 Plus 128GB,203g,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,2024,899.9964,1079.988,867.86,899.0,863.73
4,Apple,iPhone 16 Plus 256GB,203g,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,2024,935.9964,1139.988,909.86,949.0,917.73

In [23]:
# Convert columns to string first, then remove units and convert to numbers
df['Peso'] = df['Peso'].astype(str).str.replace('g', '').astype(float)
df['RAM'] = df['RAM'].astype(str).str.split('/').str[0].str.extract(r'(\d+)').astype(float)
df['camara frontal'] = df['camara frontal'].astype(str).str.split('/').str[0].str.extract(r'(\d+\.?\d*)').astype(float)
df['camara trasera'] = df['camara trasera'].astype(str).str.split('+').str[0].str.extract(r'(\d+\.?\d*)').astype(float)
df['bateria'] = df['bateria'].astype(str).str.replace(',', '').str.replace('mAh', '').astype(float)
df['tamaño pantalla'] = df['tamaño pantalla'].astype(str).str.extract(r'(\d+\.?\d*)')[0].astype(float)

In [25]:
df.head()

,Compañia,Modelo,Peso,RAM,camara frontal,camara trasera,procesador,bateria,tamaño pantalla,año de lanzamiento,precio lanzamiento (Pakistan) (USD),precio lanzamiento (India) (USD),precio lanzamiento (China) (USD),precio lanzamiento (USA) (USD),precio lanzamiento (Dubai) (USD)
0,Apple,iPhone 16 128GB,174.0,6.0,12.0,48.0,A17 Bionic,3600.0,6.1,2024,809.9964,959.988,811.86,799.0,755.73
1,Apple,iPhone 16 256GB,174.0,6.0,12.0,48.0,A17 Bionic,3600.0,6.1,2024,845.9964,1019.988,853.86,849.0,809.73
2,Apple,iPhone 16 512GB,174.0,6.0,12.0,48.0,A17 Bionic,3600.0,6.1,2024,881.9964,1079.988,909.86,899.0,863.73
3,Apple,iPhone 16 Plus 128GB,203.0,6.0,12.0,48.0,A17 Bionic,4200.0,6.7,2024,899.9964,1079.988,867.86,899.0,863.73
4,Apple,iPhone 16 Plus 256GB,203.0,6.0,12.0,48.0,A17 Bionic,4200.0,6.7,2024,935.9964,1139.988,909.86,949.0,917.73

In [28]:
df.to_excel(r"C:\Users\Usuario\Desktop\escritorio\DA-DS\datasets\mobiles_limpio.xlsx", index=False)